### ISSUE TITLE
pageMargin  does not work on iOS

### ISSUE THREAD

**Issue by davidg327** [callstack/react-native-viewpager#206] opened 2020-07-28 01:16 UTC
In android the view looks like this with pageMargin
<img width="46" alt="Captura de Pantalla 2020-07-27 a la(s) 8 10 57 p  m" src="https://user-images.githubusercontent.com/47389371/88607679-6b50ce00-d045-11ea-8006-4337a6fe46d3.png">

When I run it on iOS it doesn't look the same
<img width="93" alt="Captura de Pantalla 2020-07-27 a la(s) 8 04 24 p  m" src="https://user-images.githubusercontent.com/47389371/88607680-6d1a9180-d045-11ea-9366-84ed6e450f8c.png">

I currently have the code like this.  pageMargin={-wp(2.5)}. and as I say on android it looks good

**Comment by troZee** [comment] 2020-07-28 13:51
Could you provide a code snippet for this issue ?

**Comment by davidg327** [comment] 2020-07-28 14:54
<ViewPager
                    style={{ ...styles.homeSlider, width: this.state.containerWidth, height: (this.state.containerWidth * wp(61.5)) / wp(203.75) }}
                    initialPage={0}
                    onPageSelected={(change) => {console.log(change.nativeEvent.position, "CHANGE---------------"); this.onPageChange(change.nativeEvent.position)}}
                    pageMargin={-wp(2.5)}
                    showPageIndicator={this.props.sliders.length}
                >
                    {
                        this.props.sliders.map((slider, index) => {
                            return (
                                <View key={index} style={{ backgroundColor: 'transparent', alignItems: 'center', width: this.state.containerWidth, height: (this.state.containerWidth * wp(62.5)) / wp(206.75), justifyContent: 'center' }}>
                                    <View
                                        /* onPress={() => {
                                            // this.props.navigation.navigate('BanoExpress')
                                         }}*/
                                        style={[
                                            styles.slide,
                                            { width: this.state.containerWidth * 0.9, height: (this.state.containerWidth * 0.9 * wp(62.5)) / wp(206.75) },
                                            this.state.activeSlider === index && { width: this.state.containerWidth, height: (this.state.containerWidth * wp(62.5)) / wp(206.75) }
                                        ]}
                                    >
                                        <ImageBackground style={{ flex: 1, borderRadius: wp(5), overflow: 'hidden' }} source={{uri: `${slider.banner.img}`}}/>
                                    </View>
                                </View>
                            )
                        })
                    }
                </ViewPager>

**Comment by davidg327** [comment] 2020-08-04 13:50
<img width="878" alt="Captura de Pantalla 2020-08-04 a la(s) 8 49 52 a  m" src="https://user-images.githubusercontent.com/47389371/89301649-8916c800-d62f-11ea-9e53-63043f47e6ad.png">

**Comment by albert-carreras** [comment] 2020-10-02 18:46
Positive pageMargin works, but negative doesn't indeed.

**Comment by davidg327** [comment] 2020-10-05 13:43
neither does it work with the positive,

**Comment by MateWW** [comment] 2020-12-08 15:09
@davidg327 Positive `pageMargin` works on example app even with strange variations of `width` and `height`.
Could you provide reproduction code which will allow us to reproduce your problem?
About negative once. We currently doesn't support them and have no plan for it in nearest future. 

I'll close this issue for now. 
Fell free to reopen it with reproduction code

**Closed by MateWW** 2020-12-08 15:09 UTC
Labels: bug, ios

**Comment by urtheone** [comment] 2021-06-30 10:34
Can we support negative pageMargin in iOS？Because this is a common effect。

**Comment by urtheone** [comment] 2021-06-30 10:36
`<AnimatedPagerView
                    initialPage={0}
                    style={{ flex: 1 }}
                    pageMargin={-38}
                    offscreenPageLimit={2}`
